# baseURL = ''
# languageCode = 'en-us'
# title = 'ç§¦å›½åº†'
# theme = 'PaperMod'


baseURL: ""
title: ç§¦å›½åº†
pagination:
  pagerSize: 8
theme: PaperMod
languageCode: zh-cn

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

hasCJKLanguage: true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å«ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡,å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯
enableInlineShortcodes: true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

# permalinks:
#   # post: "/:title/"
#   post: "/:year/:month/:day/:title/"
# Configure how URLs look like per section.
permalinks:
  blog: /:section/:year/:month/:day/:slug/


defaultContentLanguage: zh # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
defaultContentLanguageInSubdir: true






params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  defaultTheme: auto # dark, light
  disableThemeToggle: true
  # title: 'ç§¦å›½åº†çš„åšå®¢' # ä¸»é¢˜
  # Content: 'æˆ‘ä»¬ç™»ä¸Šå¹¶éæˆ‘ä»¬æ‰€é€‰æ‹©çš„èˆå°,æ¼”å‡ºå¹¶éæˆ‘ä»¬æ‰€é€‰æ‹©çš„å‰§æœ¬' # æè¿°
  # keywords: [Blog, PaperMod]
  # author: ["Me", "Berry"] # multiple authors
  DateFormat: "2006-01-02" # å°†æ—¶é—´æ ¼å¼ä¿®æ”¹ä¸ºå›½å†…å¸¸ç”¨æ ¼å¼
  # showtoc: true # åœ¨æ¯ç¯‡æ–‡ç« å¼€å¤´æ˜¾ç¤ºç›®å½•
  # contact:
  #   email: info@example.org
  #   phone: +1 202-555-1212
  
  # subtitle: The Best Widgets on Earth
  # description: "ExampleSite description"



  # home-info mode
  # homeInfoParams:
  #   Title: "ç§¦å›½åº†çš„åšå®¢"
  #   Content: "æˆ‘ä»¬ç™»ä¸Šå¹¶éæˆ‘ä»¬æ‰€é€‰æ‹©çš„èˆå°,æ¼”å‡ºå¹¶éæˆ‘ä»¬æ‰€é€‰æ‹©çš„å‰§æœ¬"

  # profile-mode
  # profileMode:
  #   enabled: true # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags
  profileMode:
    enabled: true
    title: "ç§¦å›½åº†çš„åšå®¢"
    subtitle: "ğŸ‘‹æ¬¢è¿å…‰ä¸´ </br> ğŸ‘‡è”ç³»æ–¹å¼"
    imageUrl: /img/logo2.jpg
    imageWidth: 210
    imageHeight: 200
    imageTitle: QGQ
    buttons:
      - name: ğŸ‘¨ğŸ»â€ğŸ’»æŠ€æœ¯
        url: tech
      - name: ğŸ“•é˜…è¯»
        url: posts
      - name: ğŸ§³ç”Ÿæ´»
        url: life

  # images: ["/img/logo2.jpg"]
  # DateFormat: "January 2, 2006"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true # æ˜¾ç¤ºå¤åˆ¶ä»£ç æŒ‰é’®
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true 
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  # ShowShareButtons: true
  # ShowReadingTime: true
  # disableSpecialistPost: true
  displayFullLangName: true
  # ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  # ShowCodeCopyButtons: true
  hideFooter: false # éšè—é¡µè„š
  # ShowWordCounts: true
  # VisitCount: true
  ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´
  # ShowToc: true # æ˜¾ç¤ºç›®å½•
  # TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  # comments: true
  
  busuanzi:
    enable: true
    site_uv: true
    site_uv_pre: '<i class="fa fa-user"></i>'
    site_uv_post: ''
    site_pv: true
    site_pv_pre: '<i class="fa fa-eye"></i>'
    site_pv_post: ''
    page_pv: true
    page_pv_pre: '<i class="far fa-eye fa-fw"></i>'
    page_pv_post: ''





  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon_logosc/favicon.ico"
    favicon16x16: "/img/favicon_logosc/favicon-16x16.png"
    favicon32x32: "/img/favicon_logosc/favicon-32x32.png"
    apple_touch_icon: "/img/favicon_logosc/apple-touch-icon.png"
    safari_pinned_tab: "/img/favicon_logosc/android-chrome-192x192.png"
  # å„ç§å›¾æ ‡çš„åœ°å€ï¼Œå¦‚æœæ²¡æœ‰å°±å…¨éƒ¨æ³¨é‡Šæ‰
  # assets:
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "ç§¦å›½åº†çš„åšå®¢"
    icon: /img/label.png
    iconHeight: 35

  socialIcons:
    - name: github
      url: "https://github.com/QGQ931001"
    - name: site
      url:  "https://qgq931001.github.io/"
    - name: bilibili
      url: "https://space.bilibili.com/59527658"
    - name: wechat
      url: "https://gitee.com/gqishereforyou/cv/raw/master/mmqrcode1735719779047.png"
    - name: QQ
      url: "https://gitee.com/gqishereforyou/cv/raw/master/qrcode_1735719804323.jpg"
    - name: email
      url: "mailto:zhupaiqgq@nwafu.edu.cn"
    - name: RSS
      url: "index.xml"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/QGQ931001/new_hugo_blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

    # twikoo:
    #   version: 1.4.11

menu:
  main:
    - identifier: categories
      name: ç±»åˆ«ó €»ó €»ó €»ğŸ“š
      url: ./categories/
      weight: 10
    - identifier: tags
      name: æ ‡ç­¾ğŸ§¾
      url: ./tags/
      weight: 20
    - identifier: archives
      name: æ—¶é—´çº¿ğŸ“Š
      url: ./archives/
      weight: 30
    - identifier: search
      name: æœç´¢ğŸ”
      url: ./search/
      weight: 40
    - identifier: about    
      name: å…³äºğŸ‘¨ğŸ¼â€ğŸ“
      url: ./about/
      weight: 50
    # - identifier: categories
    #   name: Categories/ç±»åˆ«/ó €»ó €»ó €»ğŸ“š
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: Tags/æ ‡ç­¾/ğŸ§¾
    #   url: /tags/
    #   weight: 20
    # - identifier: archives
    #   name: Archives/æ—¶é—´çº¿/ğŸ“Š
    #   url: ../archives/
    #   weight: 30
    # - identifier: search
    #   name: Search/æœç´¢/ğŸ”
    #   url: /search/
    #   weight: 40
    # - identifier: about    
    #   name: About/å…³äº/ğŸ‘¨ğŸ¼â€ğŸ“ğŸŠğŸ¼ğŸ‹ğŸ»â€â™€ï¸
    #   url: ../about/
    #   weight: 50
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

outputs:
  home:
    - HTML
    - RSS
    - JSON 


# å…³äºè¯­æ³•é«˜äº®ï¼Œå…·ä½“ä½¿ç”¨å¯æŸ¥çœ‹https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences: true                      # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses: true                      # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax: true           #
pygmentsCodeFences: true
pygmentsOptions: "linenos=table"              # å¼€å¯æ˜¾ç¤ºè¡Œå·
pygmentsStyle: tango            

markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    # style: monokai
    style: darcula
    # codeFencesï¼šä»£ç å›´æ åŠŸèƒ½ï¼Œè¿™ä¸ªåŠŸèƒ½ä¸€èˆ¬éƒ½è¦è®¾ä¸º true çš„ï¼Œä¸ç„¶å¾ˆéš¾çœ‹ï¼Œå°±æ˜¯å¹²å·´å·´çš„-ä»£ç æ–‡å­—ï¼Œæ²¡æœ‰é¢œè‰²ã€‚
    # guessSyntaxï¼šçŒœæµ‹è¯­æ³•ï¼Œè¿™ä¸ªåŠŸèƒ½å»ºè®®è®¾ç½®ä¸º true, å¦‚æœä½ æ²¡æœ‰è®¾ç½®è¦æ˜¾ç¤ºçš„è¯­è¨€åˆ™ä¼šè‡ªåŠ¨åŒ¹é…ã€‚
    # hl_Linesï¼šé«˜äº®çš„è¡Œå·ï¼Œä¸€èˆ¬è¿™ä¸ªä¸è®¾ç½®ï¼Œå› ä¸ºæ¯ä¸ªä»£ç å—æˆ‘ä»¬å¯èƒ½å¸Œæœ›è®©é«˜äº®çš„åœ°æ–¹ä¸ä¸€æ ·ã€‚
    # lineNoStartï¼šè¡Œå·ä»ç¼–å·å‡ å¼€å§‹ï¼Œä¸€èˆ¬ä» 1 å¼€å§‹ã€‚
    # lineNosï¼šæ˜¯å¦æ˜¾ç¤ºè¡Œå·ï¼Œæˆ‘æ¯”è¾ƒå–œæ¬¢æ˜¾ç¤ºï¼Œæ‰€ä»¥æˆ‘è®¾ç½®çš„ä¸º true.
    # lineNumbersInTableï¼šä½¿ç”¨è¡¨æ¥æ ¼å¼åŒ–è¡Œå·å’Œä»£ç ,è€Œä¸æ˜¯ æ ‡ç­¾ã€‚è¿™ä¸ªå±æ€§ä¸€èˆ¬è®¾ç½®ä¸º true.
    # noClassesï¼šä½¿ç”¨ class æ ‡ç­¾ï¼Œè€Œä¸æ˜¯å†…åµŒçš„å†…è”æ ·å¼
    goldmark:
        renderer:
            unsafe: true # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯


privacy:
    vimeo:
        disabled: false
        simple: true
    twitter:
        disabled: false
        enableDNT: true
        simple: true
    instagram:
        disabled: false
        simple: true
    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true


